name: Build and deploy bundle.js

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npx vite build

      - name: Session info for tracing
        run: |
          echo "=== SESSION INFO ==="
          git status
          echo "===================="

      - name: Commit & push bundle.js
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/bundle.js
          git commit -m "chore: rebuild bundle.js from src" --allow-empty || echo "✅ No changes to commit"
          git push

      - name: Show bundled hash
        run: |
          echo "──────────────────────────────────────"
          echo "↺ bundle.js rebuilt successfully ✅"
          HASH=$(git rev-parse --short HEAD)
          echo "📦 New version hash: $HASH"
          echo "   CDN URL: https://cdn.jsdelivr.net/gh/KazuhitoKawauchi/191-tab-dashboard@${HASH}/docs/bundle.js"
          echo "──────────────────────────────────────"

